# These are supported funding model platforms
github: achmadk
buy_me_a_coffee: achmadkurnianto
custom: ['https://trakteer.id/achmad-kurnianto-rxbtv/tip', 'https://www.paypal.com/paypalme/achmadkurnianto']
